
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 15 01:03:03 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int CONST = 6;
  public static final int EQUALS = 22;
  public static final int L_PAREN = 37;
  public static final int GREATER = 24;
  public static final int CONTINUE = 15;
  public static final int NUM_CONST = 45;
  public static final int R_PAREN = 38;
  public static final int LESS = 26;
  public static final int MINUS = 18;
  public static final int ARRSORT = 49;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int COMMA = 35;
  public static final int R_SQUARE_BRACKET = 40;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int ASSIGN = 30;
  public static final int GREATER_EQUALS = 25;
  public static final int IF = 7;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 19;
  public static final int SEMI_COLON = 33;
  public static final int MOD = 21;
  public static final int L_SQUARE_BRACKET = 39;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int ARROW = 43;
  public static final int ARRMAX = 48;
  public static final int L_BRACE = 41;
  public static final int FOREACH = 16;
  public static final int COLON = 34;
  public static final int ELSE = 5;
  public static final int R_BRACE = 42;
  public static final int LESS_EQUALS = 27;
  public static final int READ = 11;
  public static final int GOTO = 51;
  public static final int WHILE = 8;
  public static final int NOT_EQUALS = 23;
  public static final int EXTENDS = 14;
  public static final int BOOL_CONST = 46;
  public static final int DEC = 32;
  public static final int LABEL = 50;
  public static final int PRINT = 10;
}

